#!/usr/bin/env python3

from jinja2 import Environment, FileSystemLoader
from string import ascii_uppercase
import argparse
import random
import math
import time
import glob
import yaml
import os

strings = {"IT": {"name": "Nome e Cognome", "id": "Matricola",
                  "date": "Data", "version": "Fila",
                  "instructions": "Istruzioni", "solution": "Soluzione",
                  "professor": "Professore", "course":"Corso"},
           "EN": {"name": "First and Last Name", "id": "Student ID",
                  "date": "Date", "version": "Version",
                  "instructions": "Instructions", "solution": "Solution",
                  "professor": "Professor", "course":"Course"}
            }
DEFAULT_HEIGHT="5cm"

parser = argparse.ArgumentParser(description='Create randomized exams based on a bank of exercises')
parser_1 = parser.add_argument_group('Exam Heading')
parser_1.add_argument('--date', type=str, default='13 Giugno 2023', help='The date of the exam')
parser_1.add_argument('--course', type=str, default='Sistemi Operativi', help='The name of the course')
parser_1.add_argument('--professor', type=str, default='Martino Trevisan', help='The name of the professor')
parser_1.add_argument('--institution', type=str, default='Università di Trieste', help='The name of the university/institution')
parser_1.add_argument('--versions', type=int, default=2, help='How many versions of the exam to create')
parser_1.add_argument('--disclaimer', type=str, default="Per ogni domanda aperta, nel caso si ritenga che manchino delle informazioni o ipotesi necessarie, le si esplicitino nello svolgimento. Si scriva nel riquadro, usando una calligrafia e una dimensione del testo che permettano una lettura agevole.", help='Instructions for the exam to print in the PDF')
parser_2 = parser.add_argument_group('Exam Building')
parser_2.add_argument('--db', type=str, default='sample-db', help='The folder of the quiz DB')
parser_2.add_argument('--structure', type=str, default="general:1,bash:1,open:1,exercize-vm:1", help='How to sample the DB. Must be a list of group:n entries, separated by comma. E.g., general:1,bash:1,open:1')
parser_2.add_argument('--outdir', type=str, default="output", help='Where to save PDFs')
parser_2.add_argument('--lang', type=str, default='IT', help='Language oh headings. Supported IT and EN')
parser_2.add_argument('--seed', type=int, default=time.time(), help='Seed of the random package')
parser_2.add_argument('--template', type=str, default="template/template.tex", help='Template to use. Defaults to "template/template.tex"')
parser_2.add_argument('--keeptex', action='store_true', help='Keep Latex source for further editing')
parser_3 = parser.add_argument_group('Question Options')
parser_3.add_argument('--randomorder', action='store_true', help='Randomize the order of questions')
parser_3.add_argument('--solutionsummary', action='store_true', help='The date of the exam')
parser_3.add_argument('--quizbegin', action='store_true', help='Put all quiz before open questions')
parser_3.add_argument('--quizrandom', action='store_true', help='Randomize quiz answer order')

# Set globals
globals().update(vars(parser.parse_args()))
random.seed(seed)

def main():

    # Check lang is supported
    if not lang in strings:
        print(f"Language {lang} not supported.")
        return 1

    # Load DB
    questions = {}
    for f in glob.glob(f"{db}/*.yml"):
        section = os.path.basename(f).split(".")[0]
        questions[section] = yaml.safe_load(open(f,"r"))

    # Parse structure
    parts =[]
    for part in structure.split(","):
        section, count = part.split(":")
        parts.append( (section,int(count)) )

    # Choose questions
    selected = []
    for section, count in parts:
        selected += random.sample(questions[section],count)

    # Default height
    for question in selected:
        if question["type"] in {"open", "exercize"} and "height" not in question:
            question["height"] = DEFAULT_HEIGHT

    # Make output directory
    os.makedirs(outdir, exist_ok=True)

    # Create versions
    for letter in ascii_uppercase[:versions]:

        # Randomize order
        if randomorder:
            random.shuffle(selected)

        # Randomize answers to quiz
        if quizrandom:
            for q in selected:
                if q["type"]=="quiz":
                    correct_sol = q["options"][q["solution"]]
                    random.shuffle(q["options"])
                    q["solution"] = q["options"].index(correct_sol)

        # Quiz first if quizbegin is set
        selected_quiz = []
        selected_other = []
        if quizbegin:
            for q in selected:
                if q["type"]=="quiz":
                    selected_quiz.append(q)
                else: 
                    selected_other.append(q)
            selected = selected_quiz
            selected += selected_other

        # Invoke Exercizes
        for question in selected:
            if question["type"]=="exercize":
                ns = {}
                exec (question["handler"], ns)
                text = ns["handler"]()
                question["question"] = text["question"]
                if "solution" in text:
                    question["solution"] = text["solution"]

        # Create the environment
        environment = Environment(loader=FileSystemLoader(os.path.dirname(template)))
        template_obj = environment.get_template(os.path.basename(template))

        # Exam Text
        content = template_obj.render(date=date, course=course, disclaimer=disclaimer,
                                      professor=professor, institution=institution,
                                      version = letter, questions = selected,
                                      solution=False, solutionsummary=solutionsummary,
                                      strings=strings[lang])

        print(content, file=open(f"{outdir}/test-{date}-vers-{letter}.tex", "w"))
        os.system(f"pdflatex -output-directory='{outdir}' '{outdir}/test-{date}-vers-{letter}.tex'")
        
        # Clean Up
        if keeptex:
            os.system(f"rm '{outdir}/test-{date}-vers-{letter}.log' '{outdir}/test-{date}-vers-{letter}.aux'")
        else:
            os.system(f"rm '{outdir}/test-{date}-vers-{letter}.log' '{outdir}/test-{date}-vers-{letter}.aux' '{outdir}/test-{date}-vers-{letter}.tex'")

        # Solution
        content = template_obj.render(date=date, course=course, disclaimer=disclaimer,
                                      professor=professor, institution=institution,
                                      version = letter, questions = selected,
                                      solution=True, solutionsummary=solutionsummary,
                                      strings=strings[lang])

        print(content, file=open(f"{outdir}/test-{date}-vers-{letter}-solution.tex", "w"))
        os.system(f"pdflatex -output-directory='{outdir}' '{outdir}/test-{date}-vers-{letter}-solution.tex'")
        

        # Clean Up
        if keeptex:
            os.system(f"rm '{outdir}/test-{date}-vers-{letter}-solution.log' '{outdir}/test-{date}-vers-{letter}-solution.aux'")
        else:
            os.system(f"rm '{outdir}/test-{date}-vers-{letter}-solution.log' '{outdir}/test-{date}-vers-{letter}-solution.aux' '{outdir}/test-{date}-vers-{letter}-solution.tex'")

if __name__ == "__main__":
    main()


